// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademico.DAL.Context;

namespace SistemaAcademico.DAL.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20181201181525_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.AlunoDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<DateTime>("Data_Nascimento");

                    b.Property<int?>("FK_Aluno_Cidade");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("Codigo");

                    b.HasIndex("FK_Aluno_Cidade");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.CidadeDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<string>("UF");

                    b.HasKey("Codigo");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.CursoDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Carga_Horaria");

                    b.Property<DateTime>("Data_Inicio");

                    b.Property<string>("Nome");

                    b.HasKey("Codigo");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.DisciplinaDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<decimal>("Valor");

                    b.HasKey("Codigo");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.NotaDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Nota_Disciplina");

                    b.Property<int?>("FK_Nota_RA");

                    b.Property<decimal>("Media");

                    b.Property<decimal>("Nota1");

                    b.Property<decimal>("Nota2");

                    b.Property<decimal>("Nota3");

                    b.HasKey("Codigo");

                    b.HasIndex("FK_Nota_Disciplina");

                    b.HasIndex("FK_Nota_RA");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.RegistroAcademicoDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_RA_Aluno");

                    b.Property<int?>("FK_RA_Curso");

                    b.Property<int>("Numero_Matricula");

                    b.Property<string>("Semestre");

                    b.HasKey("Codigo");

                    b.HasIndex("FK_RA_Aluno");

                    b.HasIndex("FK_RA_Curso");

                    b.ToTable("RegistroAcademico");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.RegistroDisciplinaDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_RD_Disciplina");

                    b.Property<int?>("FK_RD_RA");

                    b.HasKey("Codigo");

                    b.HasIndex("FK_RD_Disciplina");

                    b.HasIndex("FK_RD_RA");

                    b.ToTable("RegistroDisciplina");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.AlunoDAO", b =>
                {
                    b.HasOne("SistemaAcademico.DAL.Entidades.CidadeDAO", "Cidade")
                        .WithMany()
                        .HasForeignKey("FK_Aluno_Cidade");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.NotaDAO", b =>
                {
                    b.HasOne("SistemaAcademico.DAL.Entidades.DisciplinaDAO", "Disciplina")
                        .WithMany()
                        .HasForeignKey("FK_Nota_Disciplina")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaAcademico.DAL.Entidades.RegistroAcademicoDAO", "Registro_Academico")
                        .WithMany()
                        .HasForeignKey("FK_Nota_RA");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.RegistroAcademicoDAO", b =>
                {
                    b.HasOne("SistemaAcademico.DAL.Entidades.AlunoDAO", "Aluno")
                        .WithMany()
                        .HasForeignKey("FK_RA_Aluno")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaAcademico.DAL.Entidades.CursoDAO", "Curso")
                        .WithMany()
                        .HasForeignKey("FK_RA_Curso");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.RegistroDisciplinaDAO", b =>
                {
                    b.HasOne("SistemaAcademico.DAL.Entidades.DisciplinaDAO", "Disciplina")
                        .WithMany()
                        .HasForeignKey("FK_RD_Disciplina")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaAcademico.DAL.Entidades.RegistroAcademicoDAO", "Registro_Academico")
                        .WithMany()
                        .HasForeignKey("FK_RD_RA");
                });
#pragma warning restore 612, 618
        }
    }
}
