// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademico.DAL.Context;

namespace SistemaAcademico.DAL.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.AlunoDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<DateTime>("Data_Nascimento");

                    b.Property<int>("Id_Cidade");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("Codigo");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.CidadeDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<string>("UF");

                    b.HasKey("Codigo");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.CursoDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Carga_Horaria");

                    b.Property<DateTime>("Data_Inicio");

                    b.Property<string>("Nome");

                    b.HasKey("Codigo");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.DisciplinaDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<decimal>("Valor");

                    b.HasKey("Codigo");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.NotaDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Disciplina");

                    b.Property<int>("Id_Registro_Academico");

                    b.Property<decimal>("Media");

                    b.Property<decimal>("Nota1");

                    b.Property<decimal>("Nota2");

                    b.Property<decimal>("Nota3");

                    b.HasKey("Codigo");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.RegistroAcademicoDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Aluno");

                    b.Property<int>("Id_Curso");

                    b.Property<int>("Numero_Matricula");

                    b.Property<string>("Semestre");

                    b.HasKey("Codigo");

                    b.ToTable("RegistroAcademico");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Entidades.RegistroDisciplinaDAO", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Disciplina");

                    b.Property<int>("Id_Registro_Academico");

                    b.HasKey("Codigo");

                    b.ToTable("RegistroDisciplina");
                });
#pragma warning restore 612, 618
        }
    }
}
